# permissions for end users to view kuduclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuducluster-viewer-role
rules:
- apiGroups:
  - kudu.apache.org
  resources:
  - kuduclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kudu.apache.org
  resources:
  - kuduclusters/status
  verbs:
  - get
