# permissions for end users to edit kuduclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuducluster-editor-role
rules:
- apiGroups:
  - kudu.apache.org
  resources:
  - kuduclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kudu.apache.org
  resources:
  - kuduclusters/status
  verbs:
  - get
